GET http://18.234.82.3:5000/welcome
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI4ZWNmODYzYzI0ZDZiOTAzOGM3NDM1IiwidXNlcm5hbWUiOiJqb2huMTIzIiwiaWF0IjoxNjUzNjg4MzQ0LCJleHAiOjE2NTM2ODkyNDR9.4qnCD7EUig88lPiz7BFmdAAx6j2u8TikWjvt_18zJdw

###

POSt http://18.234.82.3:5000/api/user/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI4ZWNmODYzYzI0ZDZiOTAzOGM3NDM1IiwidXNlcm5hbWUiOiJqb2huMTIzIiwiaWF0IjoxNjUzNjg4NjA2fQ.2fX3i7YKrjJW_Hmb-SllC3VOz49-KvuKRccdym_Q1as"
}

###
POST http://18.234.82.3:5000/api/user/register
Content-Type: application/json

{
  "username": "kazys123",
  "email": "vasdajsdas@mail.com",
  "password": "password123"
}

###
POST http://18.234.82.3:5000/api/user/login
Content-Type: application/json

{
  "username": "john123",
  "password": "password123"
}

###
DELETE http://18.234.82.3:5000/api/user/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI4ZWNmODYzYzI0ZDZiOTAzOGM3NDM1IiwidXNlcm5hbWUiOiJqb2huMTIzIiwiaWF0IjoxNjUzNjg4MDIxfQ.a7NemjuL9iecyBLBOjYyo6s6XKSqsH0RleSUH4GWU2U"
}

###
POST http://18.234.82.3:5000/api/user/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI4ZWNmODYzYzI0ZDZiOTAzOGM3NDM1IiwidXNlcm5hbWUiOiJqb2huMTIzIiwiaWF0IjoxNjUzNjg4MDIxLCJleHAiOjE2NTM2ODg5MjF9.7Va5zNQY2YUzHWQCG0_ej1xyOpdnbFwdce9i42_Jfmo
Content-Type: application/json

{
  "oldPassword": "password123",
  "newPassword": "admin123"
}