GET http://18.234.82.3:5000/api/wine/wines

###
GET http://18.234.82.3:5000/api/wine/wines/0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI4ZWNmODYzYzI0ZDZiOTAzOGM3NDM1IiwidXNlcm5hbWUiOiJqb2huMTIzIiwiaWF0IjoxNjUzNjg4ODIzLCJleHAiOjE2NTM2ODk3MjN9.xu2c3f7SCCe_umcjsGDZhNfbcrKlUES1Fh9pduP4DV8

###
POST http://18.234.82.3:5000/api/wine/wines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI4ZWNmODYzYzI0ZDZiOTAzOGM3NDM1IiwidXNlcm5hbWUiOiJqb2huMTIzIiwiaWF0IjoxNjUzNTI4MzUxLCJleHAiOjE2NTM1MjkyNTF9.Y8kGbXR9A58LMZTpOvrLMpQeXsk-_aXJSOyyJ62Fo5g
Content-Type: application/json

{
  "title": "Antinori Tignanello",
  "region": "Tuscany, Italy",
  "year": "2018"
}
