GET http://52.70.74.83:5000/api/wine/wines

###
GET http://52.70.74.83:5000/api/wine/wines/0

###
POST http://52.70.74.83:5000/api/wine/wines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI4ZWNmODYzYzI0ZDZiOTAzOGM3NDM1IiwidXNlcm5hbWUiOiJqb2huMTIzIiwiaWF0IjoxNjUzNzAyMTAyLCJleHAiOjE2NTM3MDMwMDJ9.BzFfUglpRHo-w7pzW5SgB05JnQLJIyrpUfeU_gxHNJs
Content-Type: application/json

{
  "title": "Antinori Tignanello",
  "region": "Tuscany, Italy",
  "year": "2018"
}
